### ISSUE TITLE
Continuous error Authorization required

### ISSUE THREAD

**Issue by PENDOnl** [youngguns-nl/moneybird_php_api#66]
Since I've changed my MB password I receive the error 'Authorization required' on every request. Can't seem to find out what the issue is or how to get this fixed. Any ideas?

Code I use is:

		$config = array(
				'clientname' => 'my-subdomain',
				'emailaddress' => 'my-email',
				'password' => 'my-password'
			);
			
			// Create a Transport
			$transport = new Moneybird\HttpClient();
			$transport->setAuth(
				$config['emailaddress'],
				$config['password']
			);
			
			$connector = new Moneybird\ApiConnector(
				$config['clientname'],
				$transport, 
				new Moneybird\XmlMapper() // create a mapper
			);
			
			// Invoice Service
			$invoiceDetails = array();
			$invoiceDetails['invoice_id'] = '2015-0001';

			$invoiceService = $connector->getService('Invoice');
			$invoice = $invoiceService->getByInvoiceId($invoiceDetails['invoice_id']);

The error occures when the 2nd line (getByInvoiceId) is called.

**Comment by pluijm** [comment]
Well, are you sure you've got the right password?

**Comment by PENDOnl** [comment]
Positive. Changed it a few times to test.

**Comment by pluijm** [comment]
Could you contact MB to verify they are seeing this auth errors too?

**Comment by PENDOnl** [comment]
Strange enough, the script seems to be working right now without any changes. I'm pretty sure it wasn't a caching issue, maybe a temporary error on the MB API's end? Anyway, thanks for the help I guess :-)
