### ISSUE TITLE
Cannot create new invoice

### ISSUE THREAD

**Issue by dennisveenhof** [youngguns-nl/moneybird_php_api#77]
Hi, When i am trying to create a new invoice i get an error. I used the example code.

Fatal error: Uncaught exception 'Moneybird\HttpClient\HttpStatusException' with message 'Unprocessable entity' in /home/tbsvwbooth/domains/vw-photobooth.nl/public_html/planning/moneybird/HttpClient.php:321 Stack trace: #0 /home/tbsvwbooth/domains/vw-photobooth.nl/public_html/planning/moneybird/HttpClient.php(384): Moneybird\HttpClient->handleError() #1 /home/tbsvwbooth/domains/vw-photobooth.nl/public_html/planning/moneybird/HttpClient.php(293): Moneybird\HttpClient->exec() #2 /home/tbsvwbooth/domains/vw-photobooth.nl/public_html/planning/moneybird/ApiConnector.php(208): Moneybird\HttpClient->send('https://dennisv...', 'POST', '<?xml version="...', Array) #3 /home/tbsvwbooth/domains/vw-photobooth.nl/public_html/planning/moneybird/ApiConnector.php(262): Moneybird\ApiConnector->request('https://dennisv...', 'POST', '<?xml version="...') #4 /home/tbsvwbooth/domains/vw-photobooth.nl/public_html/planning/moneybird/Invoice/Service.php(96): Moneybird\ApiConnector->save(Object(Moneybird\Invoice)) #5 /home/tbsvwbooth/domains/vw-pho in /home/tbsvwbooth/domains/vw-photobooth.nl/public_html/planning/moneybird/ApiConnector.php on line 236

**Comment by pluijm** [comment]
Probably invalid data is used on the invoice. You can contact MB for more information (provide them with the data posted)

**Comment by dennisveenhof** [comment]
Thanks for the reply. Found the problem. using trail version and had allready 3 invoices so thats why the error comes up. Remove de invoices and working!!!!
